import React from "react"
import Layout from "../../components/layout/layout"

// components
import Hero from "../../components/hero/hero"
import CardComponent from "../../components/card/card"
import Button from "../../components/button/button"
import SEO from "../../components/seo/seo"

// icons
import pintIcon from "../../images/icons/pint-icon.svg"

const PrivacyPolicy = () => {
    return (
        <Layout>

            <SEO title="Privacy Policy" description="The Pint & Pony | Privacy policy & cookie statement" />

            <Hero title="Privacy Policy" />

            <main className="container internal-main">

                <div className="row">
                    <div className="col-md-8">

                        <h2>1. Introduction</h2>
                        <p>1.1 We are committed to safeguarding the privacy of The Pint & Pony website visitors, service users, individual customers and customer personnel.</p>
                        <p>1.2 This policy applies where we are acting as a data controller with respect to the personal data of such persons; in other words, where we determine the purposes and means of the processing of that personal data.</p>
                        <p>1.3 Our website incorporates privacy controls which affect how we will process your personal data. By using the privacy controls, you can specify whether you would like to receive direct marketing communications and limit the collection, sharing and publication of your personal data. You can access the privacy controls via <span style={{color: "red"}}>[URL]</span>.</p>
                        <p>1.4 We use cookies on our website. Insofar as those cookies are not strictly necessary for the provision of our website and services, we will ask you to consent to our use of cookies when you first visit our website.</p>
                        
                        <h2>2. Credit</h2>
                        <p>2.1 This document was created using a template from Docular (<a href="https://seqlegal.com/free-legal-documents/privacy-policy">https://seqlegal.com/free-legal-documents/privacy-policy</a>).</p>
                        
                        <h2>3. The personal data that we collect</h2>
                        <p>3.1 In this Section 3 we have set out the general categories of personal data that we process and, in the case of personal data that we did not obtain directly from you, information about the source and specific categories of that data.</p>
                        <p>3.2 We may process data enabling us to get in touch with you ("contact data"). The contact data may include your name, email address, telephone number, postal address and/or social media account identifiers. The source of the contact data is you. If you log into our website using a social media account, we will obtain elements of the contact data from the relevant social media account provider.</p>
                        <p>3.3 We may process your website user account data ("account data"). The account data may include your account identifier, name, email address, business name, account creation and modification dates, website settings and marketing preferences. The primary source of the account data is you and/or your employer, although some elements of the account data may be generated by our website. If you log into our website using a social media account, we will obtain elements of the account data from the relevant social media account provider.</p>
                        <p>3.4 We may process information relating to transactions, including purchases of goods and/or services, that you enter into with us and/or through our website ("transaction data"). The transaction data may include your name, your contact details, your payment card details (or other payment details) and the transaction details. The source of the transaction data is you and/or our payment services provider.</p>
                        <p>3.5 We may process information contained in or relating to any communication that you send to us or that we send to you ("communication data"). The communication data may include the communication content and metadata associated with the communication. Our website will generate the metadata associated with communications made using the website contact forms.</p>
                        <p>3.6 We may process data about your use of our website and services ("usage data"). The usage data may include your IP address, geographical location, browser type and version, operating system, referral source, length of visit, page views and website navigation paths, as well as information about the timing, frequency and pattern of your service use. The source of the usage data is our analytics tracking system.</p>
                        
                        <h2>4. Purposes of processing and legal bases</h2>
                        <p>4.1 In this Section 4, we have set out the purposes for which we may process personal data and the legal bases of the processing.</p>
                        <p>4.2 Operations - We may process your personal data for the purposes of operating our website, the processing and fulfilment of orders, providing our services, supplying our goods, generating invoices, bills and other payment-related documentation, and credit control. The legal basis for this processing is our legitimate interests, namely the proper administration of our website, services and business.</p>
                        <p>4.3 Publications - We may process account data for the purposes of publishing such data on our website and elsewhere through our services in accordance with your express instructions. The legal basis for this processing is consent OR [our legitimate interests, namely [the publication of content in the ordinary course of our operations]] OR [the performance of a contract between you and us and/or taking steps, at your request, to enter into such a contract] OR <span style={{color: "red"}}>[[specify basis]]</span>.</p>
                        <p>4.4 Relationships and communications - We may process contact data, account data, transaction data and/or communication data for the purposes of managing our relationships, communicating with you (excluding communicating for the purposes of direct marketing) by email, SMS, post, fax and/or telephone, providing support services and complaint handling. The legal basis for this processing is our legitimate interests, namely communications with our website visitors, service users, individual customers and customer personnel, the maintenance of relationships, and the proper administration of our website, services and business.</p>
                        <p>4.5 Direct marketing - We may process contact data, account data and/or transaction data for the purposes of creating, targeting and sending direct marketing communications by email, SMS, post and/or fax and making contact by telephone for marketing-related purposes. The legal basis for this processing is consent OR our legitimate interests, namely promoting our business and communicating marketing messages and offers to our website visitors and service users.</p>
                        <p>4.6 Research and analysis - We may process usage data and/or transaction data for the purposes of researching and analysing the use of our website and services, as well as researching and analysing other interactions with our business. The legal basis for this processing is our legitimate interests, namely monitoring, supporting, improving and securing our website, services and business generally.</p>
                        <p>4.7 Record keeping - We may process your personal data for the purposes of creating and maintaining our databases, back-up copies of our databases and our business records generally. The legal basis for this processing is our legitimate interests, namely ensuring that we have access to all the information we need to properly and efficiently run our business in accordance with this policy.</p>
                        <p>4.8 Security - We may process your personal data for the purposes of security and the prevention of fraud and other criminal activity. The legal basis of this processing is our legitimate interests, namely the protection of our website, services and business, and the protection of others.</p>
                        <p>4.9 Insurance and risk management - We may process your personal data where necessary for the purposes of obtaining or maintaining insurance coverage, managing risks and/or obtaining professional advice. The legal basis for this processing is our legitimate interests, namely the proper protection of our business against risks.</p>
                        <p>4.10 Legal claims - We may process your personal data where necessary for [the establishment, exercise or defence of legal claims, whether in court proceedings or in an administrative or out-of-court procedure. The legal basis for this processing is our legitimate interests, namely [the protection and assertion of our legal rights, your legal rights and the legal rights of others].</p>
                        <p>4.11 Legal compliance and vital interests - We may also process your personal data where such processing is necessary for compliance with a legal obligation to which we are subject or in order to protect your vital interests or the vital interests of another natural person.</p>
                        
                        <h2>5. Providing your personal data to others</h2>
                        <p>5.1 We may disclose your personal data to our insurers and/or professional advisers insofar as reasonably necessary for the purposes of obtaining or maintaining insurance coverage, managing risks, obtaining professional advice.</p>
                        <p>5.2 Your personal data held in our website database will be stored on the servers of our hosting services providers <a href="https://www.fasthosts.co.uk">https://www.fasthosts.co.uk</a>.</p>
                        <p>5.3 We may disclose account data to our suppliers or subcontractors insofar as reasonably necessary for the proper administration of our website, services and business.</p>
                        <p>5.4 Financial transactions relating to our website and services are handled by our payment services providers, <span style={{color: "red"}}>[identify PSPs]</span>. We will share transaction data with our payment services providers only to the extent necessary for the purposes of [processing your payments, refunding such payments and dealing with complaints and queries relating to such payments and refunds]. You can find information about the payment services providers' privacy policies and practices at <span style={{color: "red"}}>[URLs]</span>.</p>
                        <p>5.5 In addition to the specific disclosures of personal data set out in this Section 5, we may disclose your personal data where such disclosure is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person. We may also disclose your personal data where such disclosure is necessary for the establishment, exercise, or defence of legal claims, whether in court proceedings or in an administrative or out-of-court procedure.</p>
                        
                        <h2>6. International transfers of your personal data</h2>
                        <p>6.1 In this Section 6, we provide information about the circumstances in which your personal data may be transferred to [countries outside the United Kingdom and the European Economic Area (EEA)].</p>
                        <p>6.2 You acknowledge that personal data that you submit for publication through our website or services may be available, via the internet, around the world. We cannot prevent the use (or misuse) of such personal data by others.</p>
                        
                        <h2>7. Retaining and deleting personal data</h2>
                        <p>7.1 This Section 7 sets out our data retention policies and procedures, which are designed to help ensure that we comply with our legal obligations in relation to the retention and deletion of personal data.</p>
                        <p>7.2 Personal data that we process for any purpose or purposes shall not be kept for longer than is necessary for that purpose or those purposes.</p>
                        <p>7.3 We will retain your personal data as follows:</p>
                        <ul style={{listStyleType: "lower-latin"}}>
                            <li>contact data will be retained for a minimum period of 18 months following the date of the most recent contact between you and us, and for a maximum period of 7 years following that date;</li>
                            <li>account data will be retained for a minimum period of 18 months following the date of closure of the relevant account, and for a maximum period of 7 years following that date;</li>
                            <li>transaction data will be retained for a minimum period of 18 months following the date of the transaction, and for a maximum period of 7 years following that date];</li>
                            <li>[communication data will be retained for a minimum period of 18 months following the date of the communication in question, and for a maximum period of 7 years following that date;</li>
                            <li>usage data will be retained following the date of collection; </li>
                            <li>data category will be retained for a minimum period of 18 months following the date of its collection, and for a maximum period of 7 years following that date.</li>
                        </ul>
                        <p>7.4 Notwithstanding the other provisions of this Section 7, we may retain your personal data where such retention is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person.</p>
                        
                        <h2>8. Your rights</h2>
                        <p>8.1 In this Section 8, we have listed the rights that you have under data protection law.</p>
                        <p>8.2 Your principal rights under data protection law are:</p>
                        <ul style={{listStyleType: "lower-latin"}}>
                            <li>the right to access - you can ask for copies of your personal data;</li>
                            <li>the right to rectification - you can ask us to rectify inaccurate personal data and to complete incomplete personal data;</li>
                            <li>the right to erasure - you can ask us to erase your personal data;</li>
                            <li>the right to restrict processing - you can ask us to restrict the processing of your personal data;</li>
                            <li>the right to object to processing - you can object to the processing of your personal data;</li>
                            <li>the right to data portability - you can ask that we transfer your personal data to another organisation or to you;</li>
                            <li>the right to complain to a supervisory authority - you can complain about our processing of your personal data; and</li>
                            <li>the right to withdraw consent - to the extent that the legal basis of our processing of your personal data is consent, you can withdraw that consent.</li>
                        </ul>
                        <p>8.3 These rights are subject to certain limitations and exceptions. You can learn more about the rights of data subjects by visiting <a href="https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/">https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/</a>.</p>
                        <p>8.4 You may exercise any of your rights in relation to your personal data [by written notice to us, using the contact details set out below].</p>
                        
                        <h2>9. About cookies</h2>
                        <p>9.1 A cookie is a file containing an identifier (a string of letters and numbers) that is sent by a web server to a web browser and is stored by the browser. The identifier is then sent back to the server each time the browser requests a page from the server.</p>
                        <p>9.2 Cookies may be either "persistent" cookies or "session" cookies: a persistent cookie will be stored by a web browser and will remain valid until its set expiry date, unless deleted by the user before the expiry date; a session cookie, on the other hand, will expire at the end of the user session, when the web browser is closed.</p>
                        <p>9.3 Cookies may not contain any information that personally identifies a user, but personal data that we store about you may be linked to the information stored in and obtained from cookies.</p>
                        
                        <h2>10. Cookies that we use</h2>
                        <p>10.1 Types of cookies we use;</p>
                        <ul style={{listStyleType: "lower-latin"}}>
                            <li>Strictly necessary cookies - These are cookies that are required for the operation of our website. They include, for example, cookies that enable you to log into secure areas of our website, use a shopping basket or make use of e-billing services.</li>
                            <li>Analytical/performance cookies - They allow us to recognise and count the number of visitors and to see how visitors move around our website when they are using it. This helps us to improve the way our website works, for example, by ensuring that users are finding what they are looking for easily.</li>
                            <li>Functionality cookies - These are used to recognise you when you return to our website. This enables us to personalise our content for you, greet you by name and remember your preferences (for example, your choice of language or region).</li>
                        </ul>
                        <p>10.2  We use cookies for the following purposes:</p>
                        <ul style={{listStyleType: "lower-latin"}}>
                            <li>authentication and status - we use cookies to identify you when you visit our website and as you navigate our website, and to help us determine if you are logged into our website (cookies used for this purpose are: Strictly necessary cookies, Analytical/performance cookies and Functionality cookies.);</li>
                            <li>shopping cart - we use cookies to maintain the state of your shopping cart as you navigate our website (cookies used for this purpose are: Strictly necessary cookies, Analytical/performance cookies and Functionality cookies.);</li>
                            <li>personalisation - we use cookies to store information about your preferences and to personalise our website for you (cookies used for this purpose are: Strictly necessary cookies, Analytical/performance cookies and Functionality cookies.);</li>
                            <li>security - we use cookies as an element of the security measures used to protect user accounts, including preventing fraudulent use of login credentials, and to protect our website and services generally (cookies used for this purpose are: Strictly necessary cookies, Analytical/performance cookies and Functionality cookies.)</li>
                            <li>advertising - we use cookies to help us to display advertisements that will be relevant to you (cookies used for this purpose are: Strictly necessary cookies, Analytical/performance cookies and Functionality cookies.);</li>
                            <li>analysis - we use cookies [to help us to analyse the use and performance of our website and services (cookies used for this purpose are: Strictly necessary cookies, Analytical/performance cookies and Functionality cookies.)</li>
                            <li>cookie consent - we use cookies to store your preferences in relation to the use of cookies more generally (cookies used for this purpose are: Strictly necessary cookies, Analytical/performance cookies and Functionality cookies).</li>
                        </ul>
                        
                        <h2>11. Cookies used by our service providers</h2>
                        <p>11.1  Our service providers use cookies and those cookies may be stored on your computer when you visit our website.</p>
                        <p>11.2  We use Google Analytics. Google Analytics gathers information about the use of our website by means of cookies. The information gathered is used to create reports about the use of our website. You can find out more about Google's use of information by visiting <a href="https://www.google.com/policies/privacy/partners/">https://www.google.com/policies/privacy/partners/</a> and you can review Google's privacy policy at <a href="https://policies.google.com/privacy">https://policies.google.com/privacy</a>.[ The relevant cookies are: <span style={{color: "red"}}>[identify cookies]</span>.]</p>
                        
                        <h2>12. Managing cookies</h2>
                        <p>12.1  Most browsers allow you to refuse to accept cookies and to delete cookies. The methods for doing so vary from browser to browser, and from version to version. You can however obtain up-to-date information about blocking and deleting cookies via these links:</p>
                        <ul style={{listStyleType: "lower-latin"}}>
                            <li><a href="https://support.google.com/chrome/answer/95647">https://support.google.com/chrome/answer/95647</a> (Chrome);</li>
                            <li><a href="https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences">https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences</a> (Firefox);</li>
                            <li><a href="https://help.opera.com/en/latest/security-and-privacy/">https://help.opera.com/en/latest/security-and-privacy/</a> (Opera);</li>
                            <li><a href="https://support.microsoft.com/en-gb/help/17442/windows-internet-explorer-delete-manage-cookies">https://support.microsoft.com/en-gb/help/17442/windows-internet-explorer-delete-manage-cookies</a> (Internet Explorer);</li>
                            <li><a href="https://support.apple.com/en-gb/guide/safari/manage-cookies-and-website-data-sfri11471/mac">https://support.apple.com/en-gb/guide/safari/manage-cookies-and-website-data-sfri11471/mac</a> (Safari); and</li>
                            <li><a href="https://privacy.microsoft.com/en-us/windows-10-microsoft-edge-and-privacy">https://privacy.microsoft.com/en-us/windows-10-microsoft-edge-and-privacy</a> (Edge).</li>
                        </ul> 
                        <p>12.2 Blocking all cookies will have a negative impact upon the usability of many websites.</p>
                        <p>12.3 If you block cookies, you will not be able to use all the features on our website.</p>
                        
                        <h2>13. Amendments</h2>
                        <p>13.1 We may update this policy from time to time by publishing a new version on our website.</p>
                        <p>13.2 You should check this page occasionally to ensure you are happy with any changes to this policy.</p>
                        <p>13.3 We may notify you of significant changes to this policy by email.</p>
                        
                        <h2>14. Our details</h2>
                        <p>14.1 This website is owned and operated by The Pint & Pony Ltd</p>
                        <p>14.2 We are registered in England and Wales under registration number <span style={{color: "red"}}>[number]</span>, and our registered office is at <span style={{color: "red"}}>[address]</span>.</p>
                        <p>14.3 Our principal place of business is at <span style={{color: "red"}}>[address]</span>.</p>
                        <p>14.4 You can contact us:</p>
                        <ul style={{listStyleType: "lower-latin"}}>
                            <li>[using our website contact form];</li>
                            <li>by telephone, on the contact number published on our website;</li>
                            <li>by email, using the email address published on our website.</li>
                        </ul>
                        
                        <h2>15. Data protection officer</h2>
                        <p>15.1 Our data protection officer's contact details are: <a href="mailto:info@thepintandpony.co.uk">info@thepintandpony.co.uk</a></p>

                    </div>
                    <div className="col-md-4">
                        <CardComponent colour="green" title="Our packages" icon={pintIcon} columnWidth="small">
                            <p>Want to find out how we can be the perfect addition to your event? Check out our package and pricing options.</p>
                            <Button type="cta" embedded="true" link="/packages">Find out more</Button>
                        </CardComponent>
                    </div>
                </div>

            </main>
        </Layout>
    )
}

export default PrivacyPolicy